minor_changes:
  - "Antsibull-changelog now uses Pydantic to parse and validate the config.
     This means that validation is more strict than before and might reject configs that were incorrect, but still got accepted somehow
     (https://github.com/ansible-community/antsibull-changelog/pull/193)."
  - "Antsibull-changelog now depends on Pydantic 2 (https://github.com/ansible-community/antsibull-changelog/pull/193)."
breaking_changes:
  - "When using antsibull-changelog as a library, ``ChangelogConfig``'s constructor should no longer be called directly.
     Instead, use the class method ``ChangelogConfig.parse()``, which has the same signature than the previous constructor,
     except that ``ignore_is_other_project`` now must be a keyword parameter
     (https://github.com/ansible-community/antsibull-changelog/pull/193)."
