---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

name: Test antsibull-changelog lint-changelog-yaml subcommand

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Run once per week (Friday at 06:00 UTC)
  schedule:
    - cron: '0 6 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.11'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          sed -i -e 's/^python = .*/python = "^${{ matrix.python-version }}"/' pyproject.toml
          poetry install

      - name: Check out community.general's stable-4 branch
        uses: actions/checkout@v3
        with:
          repository: ansible-collections/community.general
          ref: stable-4
          path: community.general

      - name: antsibull-changelog lint-changelog-yaml (community.general changelog)
        run: |
          poetry run coverage run -p --source antsibull_changelog -m antsibull_changelog.cli lint-changelog-yaml community.general/changelogs/changelog.yaml

      - name: antsibull-changelog lint-changelog-yaml (own changelog)
        run: |
          poetry run coverage run -p --source antsibull_changelog -m antsibull_changelog.cli lint-changelog-yaml --no-semantic-versioning changelogs/changelog.yaml

      - name: antsibull-changelog lint (own changelog fragments)
        run: |
          poetry run coverage run -p --source antsibull_changelog -m antsibull_changelog.cli lint

      - name: Combine and upload coverage stats
        run: |
          poetry run coverage combine .coverage.*
          poetry run coverage report
          poetry run coverage xml -i
          poetry run codecov
